$u = @()
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_b.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ba.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ba1.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ba2.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_baba.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_bi.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_bi3.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_bo.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_bu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_d.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_da.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_da4.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_de.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_di.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_didi.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_du.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_du2.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_f.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_fa.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_fo.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_fu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_fu2.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_l.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_la.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_la1.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_le.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_li.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_liwu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_lu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_lv.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_m.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ma.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_malu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mama.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_me.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mi.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mo.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_muma.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mv.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mü.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_mü3.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_n.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_na.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_na2.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ne.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ni.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_nu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_nv3.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_p.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_pa.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_pa2.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_pa4.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_pi.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_po.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_pu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_t.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ta.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_te.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ti.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_ti1.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_tu.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_tu3.mp3"
$u += "https://www.mtl.moe.edu.sg/xuele/PYCB/Files/sound-moe_l2_learn_yifu.mp3"
   


$OutPath = "C:\Users\Jared\Desktop\Tingxie\"

ForEach ( $item in $u) {
$file = $OutPath +  ($item).split('/')[-1]
(New-Object System.Net.WebClient).DownloadFile($item, $file)
}